version: '3.8'
services:
  api:
    build: .
    container_name: company-matcher-api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - elastic
    env_file: .env
    command: pnpm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  postgres:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: matcher
      POSTGRES_USER: matcher
      POSTGRES_PASSWORD: matcher
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es
    platform: linux/x86_64
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
volumes:
  pgdata: {}
